### ISSUE TITLE
Unable to Use Installed Plugins Without Internet Access

### ISSUE THREAD

**Issue by BekahT** [katalon-studio/katalon-studio#135]
It looks like plugins from the plugin store can only be used with an active Internet connection. I cannot install new ones without an Internet connection and I cannot access the ones I have already installed (with Internet access) if I don't have Internet access at the time I open Katalon.

I would really like to be able to download the plugins once, then manually load them into Katalon.

**Comment by ytreister** [comment]
I am glad someone brought this up, I have been struggling with this as well.

**Comment by ytreister** [comment]
@dungleonhart  @devalex88  @longngbui 
Any chance you can get this fixed soon?  I work in an environment with no internet connectivity, and this is preventing me from potentially buying or trying out the plugins.  I wanted to play with the auto healing xpath plugin, but can't.

I would like to be able to download the plugin and install from a file or folder.

**Comment by asoltesz** [comment]
This is a huge problem.

We are developing an Automated Test System with Katalon that needs to run on inside a firewalled intranet so that Katalon Studio (running in a Docker container) cannot download plugins from the Katalon store.

I need to download and place the necessary plugins into my Docker image so that it doesn’t need to access the Katalon Store when the container is running in the private network.

However, this issue indicates that this is not even possible so we have a complete show stopper on hand.

Since now very basic functionality of Katalon has been moved to plugins (Basic Reports), it seems like Katalon becomes impossible to run in restricted environment (like banks and other enterprise intranets).

Downloading / installing plugins manually and letting the run without internet is a MUST.

**Comment by gabrielke** [comment]
I can only agree with the others, this is a showstopper in restricted environments (like a bank).

**Comment by Kenith** [comment]
showstopper +1

**Comment by Kenith** [comment]
And also, please take the ignore certificate error into considerarion

**Comment by donwelsh** [comment]
I agree, showstopper +1

**Comment by kungger888** [comment]
Hasn't this problem been solved yet?

**Comment by devalex88** [comment]
Implemented in 7.0.0. Please see https://docs.katalon.com/katalon-studio/docs/offline-plugin.html.

**Comment by Bugazelle** [comment]
Hello @devalex88 :

Would you please reopen the issue?

Because the implemented offline feature is only for KSE.
As a fan of Katalon, to be honest, since KS7.0, something is different, and taste weird now.

We could totally understand the business purpose for KSE.
But for the community, for the small team, we prefer more to free KS.
However, the KS7 has a lot of limited now, such as this offline feature.

Please keep and care the communities as the previous.
Katalon is still YOUNG.
We don't want to abandon Katalon, and we believe Katalon need us, need the community to raise up the reputation of Katalon.

Thank you,
A fan of Katalon

**Comment by zkylab** [comment]
Actually I totally agree with @Bugazelle. 

Katalon is still young and If they continue their limitations for free users, my company also will find new tools.
