### ISSUE TITLE
Katalon No report is generated when you run by console or command line

### ISSUE THREAD

**Issue by M4xweLL** [katalon-studio/katalon-studio#162]
#### Steps to reproduce:

When the test suite is run by console everything runs fine but the * .xml reports are not generated
It is strange because when the suite is run with the Katalon GUI manually everything works perfectly and the reports are generated.

What do I have to configure to make it work?

#### Command used:
C:\Katalon_Studio_Windows_64\katalon.exe -noSplash  -runMode=console -projectPath="C:\git\Paquete-Prestaciones_Katalon\Paquete-Prestaciones.prj" -retry=0 -testSuitePath="Test Suites/TestSuite1" -executionProfile="default" -browserType="Chrome"

**Comment by kalcoseba** [comment]
I have the same issue. The console execution doesn't create the HTML, PDF and CSV. Though it creates the logs (execution.properties, execution.uuid and execution0.log). Any updates on this?

**Comment by kalcoseba** [comment]
Hey M4xwell,
I solved this one just now. I found a discussion in the Katalon forum (https://forum.katalon.com/t/using-basic-report-plugin-as-of-katalon-6-1-5/25326).
Basically, what they're saying was, since the reports are put on a plug-in (Basic Reports) you have to make use of an -apiKey="{yourAPIKey}" and add it along in your command line. Here's how you can generate your own api.. (https://docs.katalon.com/katalon-store/docs/user/API-key.html#create-a-new-key). Mine works with the api key enclosed with double quotes.
The only draw back I've observed is that the PDF report is not generated. That's probably still an issue.

**Comment by M4xweLL** [comment]
@kalcoseba Thank you very much, everything you indicate had already tried it but it had a little error in syntax -apikey must be written with the letter **K** in upper case **-apiKey** and everything works!
The other problem I have is that the reports are generated but can not be read by jenkins. =)

Regards!!!

**Comment by kalcoseba** [comment]
Yep. It is case sensitive. From the other discussion, one guy was saying he needs to enclosed the API key with square brackets in order to work, but didn't for me so I enclosed (my API key) with double quotes (as what the other parameters get). For your reports, that's probably for the Jenkins part. I have my reports sent over by email and also incorporated to use the Katalon Analytics.

**Comment by kalcoseba** [comment]
Hey M4xwell,
Were you able to solve this? I think I know what you are trying to say here on the reports not being read by Jenkins..

**Comment by M4xweLL** [comment]
Thank you very much! the problem was solved as you had indicated, apologies for not closing the ticket.
