### ISSUE TITLE
Support video recording on browser-level

### ISSUE THREAD

**Issue by minhthanh3145** [katalon-studio/katalon-studio#352]
Currently video recording records the screen, if users run tests in headless mode or do something else while waiting then the recording will not be available or meaningful. 

https://forum.katalon.com/t/katalon-reports/44954

**Comment by duyluonganh** [comment]
Materials:
http://jcodec.org/
https://github.com/enyason/DesktopScreenRecorder

**Comment by staniere** [comment]
Thank you to open a feature request for that :slight_smile:
I hope this will solve my problem which is very similar : 
Recorded video get blacks when launched on katalon-runtime through VMWARE server (Because UI screen is not available when not connected within remote desktop)
https://forum.katalon.com/t/video-is-empty-when-scenario-is-launched-by-katalon-runtime-trough-jenkins-windows-instance/43974/8

**Comment by duyluonganh** [comment]
@staniere 
We are working on this feature. Please stay tuned and keep watching this issue.

**Comment by Padoplin** [comment]
Hello everyone

This new feature is available for Katalon Studio Enterprise users in version 7.8+. [Learn more](https://docs.katalon.com/katalon-studio/docs/screenshots-videos.html#browser-based-video-recorder).

Jass

**Comment by ejerskov** [comment]
Im running 7.8.1 both in Studio and Runtime Engine and I still get a black screen.

**Comment by shvasude** [comment]
@Padoplin any luck on this. I'm facing the similar issue
